apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yaml
images:
  - name: ghcr.io/pascariucosmin93/passwd
    newTag: 263f18f0320a2b7d3377dc373735a77333d290e7
