apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yaml
images:
  - name: ghcr.io/pascariucosmin93/passwd
    newTag: 64e1aed3e27e5930efd31fc68b3360e20c9d485f
