apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yaml
images:
  - name: ghcr.io/pascariucosmin93/passwd
    newTag: ed8f3d4a486016fee0d2dcd0af32523ade313ea9
