apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
type: Opaque
stringData:
  DOMAIN: "https://passwd.cosmin-lab.com"
  ADMIN_TOKEN: "schimba-ma"
  SIGNUPS_ALLOWED: "false"
  WEBSOCKET_ENABLED: "true"
  ROCKET_PORT: "80"
  TZ: "Europe/Bucharest"

